name: CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: .
          target: ~/todo-Manager
          overwrite: true
          rm: false
          strip_components: 0
          exclude: |
            .git
            node_modules
            frontend/node_modules
            backend/node_modules

      - name: Deploy via docker-compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -e
            cd C:\Users\SoumyaM\OneDrive - Talentica Software (I) Pvt. Ltd\Documents\todo-Manager
            docker-compose pull || true
            docker-compose down
            docker-compose up -d --build
            docker system prune -f || true

      - name: Verify services
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -e
            cd C:\Users\SoumyaM\OneDrive - Talentica Software (I) Pvt. Ltd\Documents\todo-Manager
            docker-compose ps
            curl -sf http://localhost:5000/health
            curl -sf http://localhost:3000 >/dev/null

      # Teams notifications are optional; kept minimal to avoid circular JSON issues
      # - name: Notify MS Teams (success)
      #   if: success()
      #   uses: skitionek/notify-microsoft-teams@v1.0.9
      #   with:
      #     webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK }}
      #     raw: |
      #       {"@type":"MessageCard","@context":"https://schema.org/extensions","summary":"CD Succeeded","text":"CD succeeded on ${{ secrets.DEPLOY_HOST }}: ${{ github.repository }}#${{ github.run_number }}"}

      # - name: Notify MS Teams (failure)
      #   if: failure()
      #   uses: skitionek/notify-microsoft-teams@v1.0.9
      #   with:
      #     webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK }}
      #     raw: |
      #       {"@type":"MessageCard","@context":"https://schema.org/extensions","summary":"CD Failed","text":"CD failed on ${{ secrets.DEPLOY_HOST }}: ${{ github.repository }}#${{ github.run_number }}"}
