name: CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start services
        run: |
          docker compose up -d --build

      - name: Wait for services
        run: |
          echo "Waiting for services to be ready..."
          sleep 20

      - name: Verify backend health
        run: |
          curl -sf http://localhost:5000/health

      - name: Verify frontend
        run: |
          curl -sf http://localhost:3000 >/dev/null

      - name: Show running services
        run: |
          docker compose ps

      - name: Show recent logs (optional)
        if: failure()
        run: |
          docker compose logs --no-color | tail -n 200 || true

      - name: Teams notification
        if: always()
        continue-on-error: true
        uses: skitionek/notify-microsoft-teams@v1.0.9
        with:
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK }}
          raw: |
            {"@type":"MessageCard","@context":"https://schema.org/extensions","summary":"CD ${{ job.status }}","text":"CD ${{ job.status }} on GitHub runner: ${{ github.repository }}#${{ github.run_number }}"}

      - name: Stop and remove services
        if: always()
        run: |
          docker compose down --remove-orphans
          docker system prune -f || true
