name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install frontend deps
        working-directory: frontend
        run: npm install

      - name: Install backend deps
        working-directory: backend
        run: npm install

      - name: Notify MS Teams (success)
        if: success()
        uses: skitionek/notify-microsoft-teams@v1.0.9
        with:
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK }}
          title: "CI succeeded"
          text: "Workflow ${{ github.workflow }} run ${{ github.run_number }} succeeded for ${{ github.repository }}@${{ github.sha }}."

      - name: Notify MS Teams (failure)
        if: failure()
        uses: skitionek/notify-microsoft-teams@v1.0.9
        with:
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK }}
          title: "CI failed"
          text: "Workflow ${{ github.workflow }} run ${{ github.run_number }} failed for ${{ github.repository }}@${{ github.sha }}. See run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
