name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install frontend deps
        working-directory: frontend
        run: npm install

      - name: Install backend deps
        working-directory: backend
        run: npm install

      - name: Teams notification
        if: always()
        continue-on-error: true
        uses: skitionek/notify-microsoft-teams@v1.0.9
        with:
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK }}
          raw: |
            {"@type":"MessageCard","@context":"https://schema.org/extensions","summary":"CI ${{ job.status }}","text":"CI ${{ job.status }}: ${{ github.repository }}#${{ github.run_number }}"}
